export const SUBMISSION_UPLOAD_LIMIT_MB = 50;
export const SUBMISSION_UPLOAD_LIMIT_BYTES =
  SUBMISSION_UPLOAD_LIMIT_MB * 1024 * 1024;
export const SUBMISSION_UPLOAD_LIMIT_LABEL = `${SUBMISSION_UPLOAD_LIMIT_MB} MB`;
